language: node_js
node_js:
  - "14"  # Specify the Node.js version if you need one

# Install necessary dependencies for HTML validation
before_install:
  - npm install -g htmlhint  # Install HTMLHint globally

# Define the script to run during the build
script:
  - htmlhint ./*.html  # Validate all HTML files in the root directory
