language: node_js
node_js:
  - "14"  # Specify the Node.js version

# Install dependencies if needed (e.g., for static site generators)
install:
  - npm install

# Script to run tests or build the site
script:
  - npm run build  # Replace with your build command if needed

# Deploy settings
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set this in your Travis CI settings
  local_dir: public  # Change this to your build directory if different
  on:
    branch: main  # Deploy only from the main branch

# Optional: Notifications for build status
notifications:
  email:
    recipients:
      - awaradiana40@gmail.com  # Replace with your email
    on_success: change
    on_failure: always

