name: Trigger Travis CI

on:
  deployment:
    types: [created]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Travis CI Build
        run: |
          curl -X POST -H "Travis-API-Version: 3" \
          -H "Authorization: token ${{ secrets.TRAVIS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"request": {"branch": "main"}}' \
          https://api.travis-ci.com/repo/<PrincessD10>%2F<test>/requests
